############# English navigation ##############

# main menu

[[main]]
name = "home"
url = ""
weight = 1

# [[main]]
# name = "about"
# url = "about/"
# weight = 10

[[main]]
name = "category"
url = "categories/"
weight = 5

[[main]]
name = "tags"
url = "tags/"
weight = 6

[[main]]
name = "records"
url = "records/"
weight = 4

# dropdown menu
# [[main]]
# name = "Pages"
# weight = 6
# hasChildren = true

#   # dropdown item
#   [[main]]
#   parent = "Pages"
#   name = "page 1"
#   url = "/"

#   [[main]]
#   parent = "Pages"
#   name = "page 2"
#   url = "/"
